### ISSUE TITLE
As a user, I want to be able to chat with other users.

### ISSUE THREAD

**Issue by syed-mohsin** [Mtroyanovsky1/Hackathon-Quonvo#1]

**Comment by Mtroyanovsky1** [comment]
Chat userflow of answerer

1.  User clicks on a question
2. Chat is opened in the answers-chat container  
3. The first message in the chat is the question that was asked
4. User can then chat with the person who asked the question 
5. User can end chat


Chat userflow of asker

1. a chat box pops up in questions-chat container
2. The first message in the chat is the question that was asked
3. User can then chat with the person who asked the question

**Comment by Mtroyanovsky1** [comment]
Chat Schema

1. Created: Date,
2. Message: Array (ObjectId.message),
3. Rating: Number, (Between 1-5)
4. Closed: Boolean
5. Asker: ObjectId.user
6. Answerer: ObjectId.user
7. Question: ObjectId.question


Message Schema 
1. Name: String, (Username from req.body)
2. To: ObjectId,
3. From: ObjectId,
4. Content: String, 
5. Created: Date
6. Chat: ObjectId.chat

**Comment by Mtroyanovsky1** [comment]
// global variable: {user : [socketIds]}


**Client:**
socket.on("getMessage", function(recvdMessage) {

});

// happens inside click handler when user clicks submit
// craft messageObject
socket.emit("sendMessage", messageObject);

**Server**
socket.on("sendMessage", function(recvdMessage) {
  // create mongoose object from received message;
  // chat.findById(msg.chat, function(){});
  // add message to chat
  // send message to chat participants
  // socket.emit("getMessage", receivedMessage)
});

**Comment by Mtroyanovsky1** [comment]
// socket for when chat is first created (client -> server)
// socket for new chat to append to container (server -> client)
// socket for when user just logged in or opens new tab (server -> client)
