### ISSUE TITLE
Build socket.io infrastructure

### ISSUE THREAD

**Issue by syed-mohsin** [Mtroyanovsky1/Hackathon-Quonvo#22]

**Comment by syed-mohsin** [comment]
https://gomix.com/#!/project/socket-io-demo

**Comment by syed-mohsin** [comment]
// Intercept Socket.io's handshake request
  io.use(function (socket, next) {
    // Use the 'cookie-parser' module to parse the request cookies
    cookieParser(config.sessionSecret)(socket.request, {}, function (err) {
      // Get the session id from the request cookies
      var sessionId = socket.request.signedCookies ? socket.request.signedCookies[config.sessionKey] : undefined;

      if (!sessionId) return next(new Error('sessionId was not found in socket.request'), false);

      // Use the mongoStorage instance to get the Express session information
      mongoStore.get(sessionId, function (err, session) {
        if (err) return next(err, false);
        if (!session) return next(new Error('session was not found for ' + sessionId), false);

        // Set the Socket.io session information
        socket.request.session = session;

        // Use Passport to populate the user details
        passport.initialize()(socket.request, {}, function () {
          passport.session()(socket.request, {}, function () {
            if (socket.request.user) {
              next(null, true);
            } else {
              next(new Error('User is not authenticated'), false);
            }
          });
        });
      });
    });
  });

**Comment by dnajafi** [comment]
http://stackoverflow.com/questions/13095418/how-to-use-passport-with-express-and-socket-io
